import {
  AlarmClock,
  AlertTriangle,
  BarChart3,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  ChevronUp,
  Circle,
  Crop,
  DollarSign,
  Download,
  Edit,
  Eye,
  EyeOff,
  FileTerminal,
  Filter,
  Image,
  Loader2,
  LogOut,
  Menu,
  MessageSquare,
  Minus,
  MoreHorizontal,
  MoreVertical,
  Plus,
  PlusCircle,
  RefreshCw,
  Search,
  Settings,
  ShoppingBag,
  Sliders,
  SlidersHorizontal,
  Trash,
  Twitter,
  Twitch,
  UploadCloud,
  User,
  Volume2,
  VolumeX,
  X,
  Angry,
  Frown,
  Laugh,
  Meh,
  SmilePlus,
  Smile,
  LayoutGrid,
  LayoutList,
  PlayCircle,
  type Icon as LucideIcon,
  type LucideProps,
} from "lucide-react";

import { BsDiscord } from "react-icons/bs";
import { FcGoogle, FcLinux } from "react-icons/fc";
import { AiFillWindows } from "react-icons/ai";
import { SiMacos } from "react-icons/si";
import { FaThumbsDown, FaThumbsUp } from "react-icons/fa";

export type Icon = LucideIcon;

export const Icons = {
  playCircle: PlayCircle,
  thumbsUp: FaThumbsUp,
  thumbsDown: FaThumbsDown,
  Linux: FcLinux,
  macos: SiMacos,
  windows: AiFillWindows,
  layoutGrid: LayoutGrid,
  layoutList: LayoutList,
  google: FcGoogle,
  twitch: Twitch,
  discord: BsDiscord,
  twitter: Twitter,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronUpDown: ChevronsUpDown,
  menu: Menu,
  verticalThreeDots: MoreVertical,
  horizontalThreeDots: MoreHorizontal,
  verticalSliders: Sliders,
  horizontalSliders: SlidersHorizontal,
  circle: Circle,
  check: Check,
  add: Plus,
  addCircle: PlusCircle,
  remove: Minus,
  view: Eye,
  hide: EyeOff,
  trash: Trash,
  edit: Edit,
  crop: Crop,
  reset: RefreshCw,
  download: Download,
  warning: AlertTriangle,
  search: Search,
  filter: Filter,
  alarm: AlarmClock,
  calendar: CalendarDays,
  user: User,
  dashboard: FileTerminal,
  settings: Settings,
  logout: LogOut,
  volume: Volume2,
  volumeMute: VolumeX,
  message: MessageSquare,
  dollarSign: DollarSign,
  store: ShoppingBag,
  chart: BarChart3,
  upload: UploadCloud,
  placeholder: Image,
  angry: Angry,
  frown: Frown,
  laugh: Laugh,
  meh: Meh,
  smilePlus: SmilePlus,
  smile: Smile,
};
